In [6]:
import pandas as pd
import numpy as np
  
import os, sys, subprocess



DATABASE = "202103-EXP.mdb" # database name 

# Get table names using mdb-tables
table_names = subprocess.Popen(['mdb-tables', '-1', DATABASE], stdout=subprocess.PIPE).communicate()[0]

table_names=table_names.decode("utf-8") 
tables = table_names.split('\n')[:-1]

print(tables)
total_csv=[]
for table in tables:
    if table != '':
        filename = table.replace(' ','_') + '.csv'
        
        filename="finallll"+filename
        total_csv.append(filename)
        print('Exporting ' + table)
        with open(filename, 'wb') as f:
            subprocess.check_call(['mdb-export', DATABASE, table], stdout=f)

['EXP']
Exporting EXP

In [19]:
count=0
all_xls_file=[]
for filename in total_csv:

    for chunk in pd.read_csv(filename, chunksize=10000):
       # importing the module

       #saving xlsx file
        
        name=table+str(count)+'.xlsx'
        print(name)
        all_xls_file.append(name)
        to_xls = pd.ExcelWriter(table+str(count)+'.xlsx')
        chunk.to_excel(to_xls, index = False)

        to_xls.save()
        count=count+1

EXP0.xlsx
EXP1.xlsx
EXP2.xlsx
EXP3.xlsx
EXP4.xlsx
EXP5.xlsx
EXP6.xlsx
EXP7.xlsx
EXP8.xlsx
EXP9.xlsx
EXP10.xlsx
EXP11.xlsx
EXP12.xlsx
EXP13.xlsx
EXP14.xlsx
EXP15.xlsx
EXP16.xlsx
EXP17.xlsx
EXP18.xlsx
EXP19.xlsx
EXP20.xlsx
EXP21.xlsx
EXP22.xlsx
EXP23.xlsx
EXP24.xlsx
EXP25.xlsx
EXP26.xlsx
EXP27.xlsx
EXP28.xlsx
EXP29.xlsx
EXP30.xlsx
EXP31.xlsx
EXP32.xlsx
EXP33.xlsx
EXP34.xlsx
EXP35.xlsx
EXP36.xlsx
EXP37.xlsx
EXP38.xlsx
EXP39.xlsx
EXP40.xlsx
EXP41.xlsx
EXP42.xlsx
EXP43.xlsx
EXP44.xlsx
EXP45.xlsx
EXP46.xlsx
EXP47.xlsx
EXP48.xlsx

In [22]:
total_csv

['finallllEXP.csv']

In [21]:
all_xls_file

['EXP0.xlsx',
 'EXP1.xlsx',
 'EXP2.xlsx',
 'EXP3.xlsx',
 'EXP4.xlsx',
 'EXP5.xlsx',
 'EXP6.xlsx',
 'EXP7.xlsx',
 'EXP8.xlsx',
 'EXP9.xlsx',
 'EXP10.xlsx',
 'EXP11.xlsx',
 'EXP12.xlsx',
 'EXP13.xlsx',
 'EXP14.xlsx',
 'EXP15.xlsx',
 'EXP16.xlsx',
 'EXP17.xlsx',
 'EXP18.xlsx',
 'EXP19.xlsx',
 'EXP20.xlsx',
 'EXP21.xlsx',
 'EXP22.xlsx',
 'EXP23.xlsx',
 'EXP24.xlsx',
 'EXP25.xlsx',
 'EXP26.xlsx',
 'EXP27.xlsx',
 'EXP28.xlsx',
 'EXP29.xlsx',
 'EXP30.xlsx',
 'EXP31.xlsx',
 'EXP32.xlsx',
 'EXP33.xlsx',
 'EXP34.xlsx',
 'EXP35.xlsx',
 'EXP36.xlsx',
 'EXP37.xlsx',
 'EXP38.xlsx',
 'EXP39.xlsx',
 'EXP40.xlsx',
 'EXP41.xlsx',
 'EXP42.xlsx',
 'EXP43.xlsx',
 'EXP44.xlsx',
 'EXP45.xlsx',
 'EXP46.xlsx',
 'EXP47.xlsx',
 'EXP48.xlsx']

In [23]:
finalexcelsheetfinal = pd.DataFrame()


for file in all_xls_file:

    print(file)
    # combining multiple excel worksheets
    # into single data frames
    df = pd.concat(pd.read_excel(
    file, sheet_name=None), ignore_index=True, sort=False)

    # appending excel files one by one
    finalexcelsheetfinal = finalexcelsheetfinal.append(df, ignore_index=True)



display(finalexcelsheetfinal)

EXP0.xlsx
EXP1.xlsx
EXP2.xlsx
EXP3.xlsx
EXP4.xlsx
EXP5.xlsx
EXP6.xlsx
EXP7.xlsx
EXP8.xlsx
EXP9.xlsx
EXP10.xlsx
EXP11.xlsx
EXP12.xlsx
EXP13.xlsx
EXP14.xlsx
EXP15.xlsx
EXP16.xlsx
EXP17.xlsx
EXP18.xlsx
EXP19.xlsx
EXP20.xlsx
EXP21.xlsx
EXP22.xlsx
EXP23.xlsx
EXP24.xlsx
EXP25.xlsx
EXP26.xlsx
EXP27.xlsx
EXP28.xlsx
EXP29.xlsx
EXP30.xlsx
EXP31.xlsx
EXP32.xlsx
EXP33.xlsx
EXP34.xlsx
EXP35.xlsx
EXP36.xlsx
EXP37.xlsx
EXP38.xlsx
EXP39.xlsx
EXP40.xlsx
EXP41.xlsx
EXP42.xlsx
EXP43.xlsx
EXP44.xlsx
EXP45.xlsx
EXP46.xlsx
EXP47.xlsx
EXP48.xlsx

,Act_Arrival_Date,Products,HS_Code,HS_Description,US_Exporter,US_Exporter_Address,Port_of_Departure,Country_of_Final_Destination,Bill_of_Lading_Nbr,Metric_Tons,...,Vessel_Name,Place_Receipt,State_of_Receipt_Place,Foreign_Port,Country_of_Foreign_Port,Final_Destination,Type_of_Cargo,Voyage,Containerized,Year
0,2021-03-01 00:00:00.000,1X40HC CONTAINER:BALESOF USED CREDENTIAL CLOTH...,61,"61 - APPAREL ARTICLES AND ACCESSORIES, KNIT OR...",GLOBAL MARINE TRANSPORTATION INC,"C/O: GARSON&SHAW LLC1120 6TH AVE FL 4NEW YORK,...","NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",Guatemala (GT),CMDUNAM4266571,19.85,...,CONTSHIP ICE,NaN,"NEW YORK, NY",PUERTO BARRIOS,GUATEMALA,NaN,NON REFRIGERATED,0UA85S1MA,Yes,2021
1,2021-03-01 00:00:00.000,1X40HC CONTAINER:PIECESHOUSEHOLD GOODSNO SED R...,00,00 - OTHERS,SHIPCO TRANSPORT INC(SEA) EIN:,13-3468377 14900 INTERURBAN AVENUESOUTH SUITE ...,"HOUSTON,TX",Philippines (PH),CMDUNAM4266497,23.22,...,BELITA,NaN,"WASHINGTON, WA",DAVAO,PHILIPPINES,NaN,NON REFRIGERATED,0PG8QW1MA,Yes,2021
2,2021-03-01 00:00:00.000,3X40HC CONTAINERS:270 BALES UNITED STATES(BCI)...,520100,"520100 - COTTON, NOT CARDED OR COMBED",OLAM COTTON,"2221 LAKESIDE BLVD, SUITE 1050RICHARDSON, TX 7...","HOUSTON,TX",Vietnam (VN),CMDUNAM4266389,61.17,...,BELITA,NaN,"TEXAS, TX","CAT LAI PORT, #",VIETNAM,NaN,NON REFRIGERATED,0PG8QW1MA,Yes,2021
3,2021-03-01 00:00:00.000,ONE 40 X 8 X 9'6 HIGH CUBE SLAC214 PIECES(001)...,95,"95 - TOYS, GAMES&SPORT EQUIPMENT; PARTS&ACCESS...",TT OCEAN LOGISTICS,10201 NW 112TH AVE SUITE 20MEDLEY FLORIDA33178...,"NEW YORK, NY",Netherlands (NL),HLCUBSC2101BQSS4,17.23,...,YM EVOLUTION,"USIND; INDIANAPOLIS, IN","INDIANA, IN",ROTTERDAM,NETHERLANDS,NLRTM; ROTTERDAM,NON REFRIGERATED,055E,Yes,2021
4,2021-03-01 00:00:00.000,3X40HC CONTAINERS:SNACKSSNACKSSNACKS21-10-1161...,1905,"1905 - BREAD, PASTRY, CAKES ETC; COMM WAFRS, E...",EXPRESS CONSOLIDATION SYSTEMS CORP,"611 U.S.HIGHWAY 46W, SUITE 205HASBROUCK HEIGHT...","NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",Trinidad & Tobago (TT),CMDUNAM4266140,15.26,...,CONTSHIP ICE,NaN,"NEW JERSEY, NJ",POINT LISAS TRINIDAD,TRINIDAD AND TOBAGO,NaN,REFRIGERATED,0UA85S1MA,Yes,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242927,2021-03-31 00:00:00.000,ONE 20 X 8 X 8'6 GENERAL PU SLAC16 BAGS(001) L...,320611,320611 - PIGMNTSPREPS CONT =>80% TITANIUM DIOX...,THE CHEMOURS COMPANY FC LLC,"1007 MARKET ST.WILMINGTON , DE 19898UNITED STATES","CHARLESTON,SC",Japan (JP),HLCUBSC210301540,187.53,...,HUMEN BRIDGE,"USMSY; NEW ORLEANS, LA","LOUISIANA, LA",KOBE,JAPAN,JPUKB; KOBE,NON REFRIGERATED,078W,Yes,2021
242928,2021-03-31 00:00:00.000,ONE 40 X 8 X 9'6 HIGH CUBE SLAC90 PACKAGE(001)...,540232,540232 - SYN FIL YN EXSEW NO RT TX NYLON YN OV...,INV PERFORMANCE SURFACES LLC,"175 TOWN PARK DRIVE, SUITE 200KENNESAWGA 30144...","CHARLESTON,SC",Japan (JP),HLCUBSC2103BHWA2,30.70,...,HUMEN BRIDGE,"USCHS; CHARLESTON, SC","SOUTH CAROLINA, SC",KOBE,JAPAN,JPUKB; KOBE,NON REFRIGERATED,078W,Yes,2021
242929,2021-03-31 00:00:00.000,ONE 40 X 8 X 9'6 HIGH CUBE SLAC866 BAG(001) AS...,39,39 - PLASTICS AND ARTICLES THEREOF,NOT AVAILABLE WO,NaN,"CHARLESTON,SC",Japan (JP),HLCUBSC2103BCTZ2,21.52,...,HUMEN BRIDGE,"USGXX; GREER, SC","SOUTH CAROLINA, SC",KOBE,JAPAN,JPUKB; KOBE,NON REFRIGERATED,078W,Yes,2021
242930,2021-03-31 00:00:00.000,ONE 40 X 8 X 9'6 HIGH CUBE SLAC73 PACKAGE(001)...,540232,540232 - SYN FIL YN EXSEW NO RT TX NYLON YN OV...,INV PERFORMANCE SURFACES LLC,"175 TOWN PARK DRIVE, SUITE 200KENNESAWGA 30144...","CHARLESTON,SC",Japan (JP),HLCUBSC2103BBWI4,13.48,...,HUMEN BRIDGE,"USCHS; CHARLESTON, SC","SOUTH CAROLINA, SC",KOBE,JAPAN,JPUKB; KOBE,NON REFRIGERATED,078W,Yes,2021
242931,2021-03-31 00:00:00.000,1 PLSTC:(1 PC) SOLAR WATERDISTILLATION KITSTC:...,8415,8415 - AIR CONDITIONING MACHINES(TEMP&HUM CHAN...,ECU WORLDWIDE USA,"2401 NW 69TH STREETMIAMI, FL. 33147, USPHONE: ...","PORT EVERGLADES,FL",TURKS AND CAICOS ISLANDS,PEVGTT002441,0.82,...,GRAND EXPRESS,NaN,"FLORIDA, FL","GRAND TURK, TC",TURKS AND CAICOS ISLANDS,"GRAND TURK, TC",NON REFRIGERATED,156S,Yes,2021

In [24]:
finalexcelsheetfinal.to_excel(r'finalexcelsheetfinal.xlsx', index=False)